### ISSUE TITLE
env variable is not defined

### ISSUE THREAD

**Issue by leadream** [cloudflare/wrangler2#1043]
### What version of `Wrangler` are you using?

2.0.3

### What operating system are you using?

MasOS 12.3.1

### Describe the Bug

I have a typescript project. I want to create some env variables in it.  My core files are like the below:

**wrangler.toml:**
```toml
name = "heron-server"
main = "src/index.ts"

[vars]
SUPABASE_URL = "https://abcxyz.supabase.co"
SERVICE_ROLE_KEY = "4567890"
```

**src/lib/supabase.ts:**
```ts
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY)

export default supabase
```

**src/types.d.ts:**
```ts
declare global {
  const SUPABASE_URL: string
  const SERVICE_ROLE_KEY: string
}
```

**tsconfig.json:**
```json
{
  "compilerOptions": {
    "target": "es2021",
    "lib": [
      "es2021"
    ],
    "module": "es2022",
    "moduleResolution": "node",
    "types": [
      "@cloudflare/workers-types"
    ],
    "resolveJsonModule": true,
    "allowJs": true,
    "checkJs": true,
    "noEmit": true,
    "isolatedModules": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "baseUrl": "src",
    "paths": {
      "@lib/*": ["lib/*"],
      "@routes/*": ["routes/*"]
    }
  },
  "include": ["src/**/*", "src/types.d.ts", "node_modules/@types/**/*"]
}
```

Then I got this error:

<img width="557" alt="image" src="https://user-images.githubusercontent.com/12868055/168830433-bb396112-ff0c-4043-b1b1-82103b77f4f6.png">

Tried to move types into `src/lib/supabase.ts`:
```ts
import { createClient } from '@supabase/supabase-js'

declare global {
  const SUPABASE_URL: string
  const SERVICE_ROLE_KEY: string
}

// Create a single supabase client for interacting with your database 
const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY)

export default supabase
```

The type error disappeared. But I got a new mistake when running `wrangler dev --local`.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/12868055/168831216-7512a5d5-717d-4c17-a8bd-890374ef83d2.png">

**Comment by threepointone** [comment]
Hi there! I'll try to explain what's going on. But first, some quick notes.

There are two "formats" for workers. The first is what we call a 'service-worker' format. Here, one defines an event listener for fetch events, and responds with responses. Notably, variables set in `[vars]` (and other bindings) will appear as globals the worker. So if you have a var, say `abc = "some string"`, and the worker like so:

```js
addEventListener("fetch", (evt: FetchEvent) => {
  evt.respondWith(new Response(`the variable value is ${abc}`));
});

// you can also listen for 'scheduled' and 'email' events
```

The other format is what we call 'modules' format. Here, we export an object with handlers which return responses. Notably, variables set in `[vars]` (and other bindings) appear on the second argument (typically called `env`). So the previous example in module format would look like this

```js
export default {
  fetch(request, env, ctx) {
    return new Response(`the variable value is ${env.abc}`);
  },
  // you can also add 'scheduled' and 'email' handlers here
};
```

`wrangler` can automatically detect whether you're writing in the "service-worker" or "module" format by the presence of the default export. So in the example you wrote, you made a `supabase` client and exported it as on `default` made wrangler think that it's a 'module' format worker, and hence the vars `SUPABASE_URL` and `SERVICE_ROLE_KEY` aren't available as globals anymore.

So you have a few options here:

- First, there's no need to export the supabase client on default at all, since it can't respond to requests.
- You can write a worker in the 'service worker' format, and access the vars as globals
- You can write a worker in the 'module' format, and the access the vars on the `env` argument

More docs here https://developers.cloudflare.com/workers/learning/migrating-to-module-workers/

I'm closing this issue, but feel free to lemme know if you have further issues.
