### ISSUE TITLE
🐛 BUG: Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by HuakunShen** [cloudflare/wrangler2#1140]
### What version of `Wrangler` are you using?

2.0.7

### What operating system are you using?

Mac M1

### Describe the Bug

When I run `wrangler publish`, I got the following error message.

```
✘ [ERROR] ✘ [ERROR] Received a bad response from the API

  
    Uncaught ReferenceError: global is not defined
      at line 10116
      at line 31795
      at line 31796
     [code: 10021]
  
  
    If you think this is a bug, please open an issue at:
    https://github.com/cloudflare/wrangler2/issues/new
```

I am publishing a Nuxt 3 app. The starter code could be published no problem, I am still trying to locate the commit that caused this error.

**Comment by HuakunShen** [comment]
I did some debugging of my code and found that it's related to socket.io.
As long as a socket is created, I cannot publish the website.

e.g.
```js
import { io } from 'socket.io-client'
const socket = io('ws://example.com/my-namespace', {
    reconnectionDelayMax: 10000,
    auth: {
      token: '123'
    },
    query: {
      'my-key': 'my-value'
    }
  })
```

Importing `io` without instantiating socket won't cause any error.

**Comment by HuakunShen** [comment]
Does the socket.io server needs to be available? Because I am using localhost during development.

**Comment by threepointone** [comment]
I think this is because socket.io is a library made for node.js, which is a different runtime that Cloudflare Workers (`global` is available only in node.js). We have a node compatibility mode, try adding `node_compat = true` to your wrangler.toml file. That said, I suspect socket.io uses a lot more than what our compat layer can provide right now. If you're interested  in using Websockets with Workers, we have docs here https://developers.cloudflare.com/workers/learning/using-websockets/.

I'm going to close this issue, but happy to discuss more. I also recommend asking questions like this on the Workers discord at https://discord.com/invite/cloudflaredev

**Comment by kxxoling** [comment]
@threepointone This is what I got if I added `node_compat=true` in `wrangler.toml`:

```
✘ [ERROR] The `nodejs_compat` compatibility flag cannot be used in conjunction with the legacy `--node-compat` flag. If you want to use the Workers runtime Node.js compatibility features, please remove the `--node-compat` argument from your CLI command or `node_compat = true` from your config file.
```

BTW, What should I do to make https://github.com/eidam/cf-workers-status-page work again?
