### ISSUE TITLE
🐛 BUG: wrangler publish --site option includes folder name

### ISSUE THREAD

**Issue by EatonZ** [cloudflare/wrangler2#1189]
### What version of `Wrangler` are you using?

2.0.8

### What operating system are you using?

Windows

### Describe the Bug

On Wrangler v1, with this toml config:

```
[site]
bucket = "dist"
```

...files would upload to KV like this, without the `dist` folder in the path:

![nodist](https://user-images.githubusercontent.com/3020941/172069993-6f8b4a9b-dc8c-4cda-81b8-c43def848d7f.png)

When migrating to Wrangler v2 and away from having a .toml file, specifying `--site="dist"` in the `wrangler publish` command includes the `dist` folder in the path:

![dist](https://user-images.githubusercontent.com/3020941/172070024-dc47b408-4551-44fe-81ce-7a2aa19b770a.png)

I don't think this should be happening.

**Comment by threepointone** [comment]
Good catch! Yeah we should fix this to use relative paths

**Comment by threepointone** [comment]
I started working on this, but realised this may actually be better behaviour. When we start supporting multiple buckets/assets per worker (as per https://github.com/cloudflare/wrangler2/issues/1162), we don't want clashes between similarly named files in different folders. Is there a functional bug to you if the prefix is kept? I suppose the first time you migrate from wrangler 1 to 2 it'll be a little slower because it'll have to upload every asset. Anything else?

**Comment by EatonZ** [comment]
@threepointone The behavior as-is renders my entire site unusable because it does not reference "dist" in its relative links.
My workaround is to remove `--site="dist"`, keeping the other options, and have a simplified toml:

```
main = "workers-site/index.js"

[site]
bucket = "dist"
```

That makes it work, but I wanted to try and not need a toml file.

If you want to keep it this way then maybe I can update my worker js to account for the prefix.

**Comment by threepointone** [comment]
Oh I see, the problem is only when using the command line form, not the toml. Ok, that may be something we can fix.

**Comment by threepointone** [comment]
I can't seem to reproduce this bug. I made a sample repo here https://github.com/threepointone/test-site-keys, cold you tell me if your setup is any different? 

Of note btw, is that you shouldn't be bothered by the keys being generated and added to your kv store, since we also generate a manifest that maps the path to the keys (that's uploaded with the worker, so it won't be visible to you), and that map does not include the root as you describe. Could you also share the version of `@cloudflare/kv-asset-handler` you've installed, as well as what specific errors you're getting?

I did discover another bug that may or may not be related, you can test it out with `npm install --save-dev https://prerelease-registry.developers.workers.dev/prs/1236/npm-package-wrangler-1236` (which installs the build corresponding to the bugfix at https://github.com/cloudflare/wrangler2/pull/1236) and see if that fixes your issues

**Comment by EatonZ** [comment]
I tested using that version and it does partially resolve the problem. All my content was 404'ing before.
Unfortunately it still includes the folder name.

When your wrangler is uploading does it start with "Uploading as dist/" for your files like the below?

![2022-06-12_16-51-40](https://user-images.githubusercontent.com/3020941/173253145-4bb18f88-675d-4c3d-92c6-c757d87b3c19.png)

**Comment by threepointone** [comment]
Yes, but that should be fine and not cause any bugs. We upload a separate manifest along with the worker that maps paths, it looks something like this 
<img width="811" alt="image" src="https://user-images.githubusercontent.com/18808/173253569-1c365a10-712c-4510-880a-07bc79e93953.png">
Are you still seeing any bugs? If so, could you make a small repo that reproduces the problem? I'd be happy to dive into it if I can reproduce your problem here.

**Comment by EatonZ** [comment]
At this point it's not causing an issue, it's just a change from the toml bucket behavior that I do not like.
In your example everything is uploaded to a "public" folder. Wouldn't it make more sense to not include that folder, and have the index.html in the root? This is how it works with the toml and site/bucket setting. I don't see the point of including the folder in the path, it makes more sense that the contents inside the folder you specify should be the root.

**Comment by threepointone** [comment]
Sorry, I'm not sure I understand. You shouldn't have to specify the root anywhere, except for `--site`, or `site.bucket` in the toml. This preserves the older behaviour. We include the name of the dir in the key of the kv store, but that shouldn't affect your app in anyway. Am I misunderstanding?

**Comment by threepointone** [comment]
To clarify, we may decide to remove the folder name in the key as well, but I just want to be sure the current behaviour isn't causing a bug for you at the moment.

**Comment by EatonZ** [comment]
There is no functional issue with it, the sites work now and my project/site is all good now. It's purely a _display_ issue at this point.

When uploading with `--site` it looks like this:

![dist](https://user-images.githubusercontent.com/3020941/172070024-dc47b408-4551-44fe-81ce-7a2aa19b770a.png)

And through toml's site/bucket:

![nodist](https://user-images.githubusercontent.com/3020941/172069993-6f8b4a9b-dc8c-4cda-81b8-c43def848d7f.png)

What I'm getting at here is that even though both of those work, I think you should update it to not include the root folder name in the path. It just makes more sense to me. You wouldn't upload the dist folder itself in a typical hosting setup -- you would only upload the contents of it and not include the dist folder itself.

**Comment by threepointone** [comment]
This is the behaviour I'm unable to reproduce. I tried it here https://github.com/threepointone/test-site-keys and got the same kinds of keys with both `--site`, and with a `site` configuration in `my.wrangler.toml`. Could you try it there with the steps in README.md and tell me if you get the same results? Or if you could make a repo that shows this behaviour, I'd be happy to dive into it. Thank you!

**Comment by threepointone** [comment]
I took a crack at fixing this anyway (i.e. removing the folder prefix) You can try it with `npm install --save-dev https://prerelease-registry.developers.workers.dev/prs/1239/npm-package-wrangler-1239` and lemme know if it works for you?

**Comment by EatonZ** [comment]
That works perfectly! Thanks!👍
