### ISSUE TITLE
🐛 BUG: Initializing project with git fails

### ISSUE THREAD

**Issue by cobyge** [cloudflare/wrangler2#1228]
### What version of `Wrangler` are you using?

2.0.9

### What operating system are you using?

WSL Ubuntu 20.04.4

### Describe the Bug

When I try to create a new project with git initialization, I get an error as show below.
Git version 2.25.1 (Latest for Ubuntu 20.04.4)

```
➜ wrangler init testproj
 ⛅️ wrangler 2.0.9
-------------------
Using npm as package manager.
✨ Created testproj/wrangler.toml
Would you like to use git to manage this Worker? (y/n)

✘ [ERROR] Command failed with exit code 128: git branch -m main

  error: refname refs/heads/master not found
  fatal: Branch rename failed


If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new/choose

➜  ~ git --version
git version 2.25.1

➜  cd testproj
➜  git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        wrangler.toml

nothing added to commit but untracked files present (use "git add" to track)

```

**Comment by petebacondarwin** [comment]
Thanks for the issue report @cobyge - this is really strange since it is saying that it cannot find the `master` branch in order to rename it but then it is on the master branch... I'll try to reproduce it myself. Do you know if this happens on other OSes?

**Comment by sunilhari** [comment]
I have read over the internet that ```git branch -m main``` works only when you have initial commit .( Although this is not the behaviour in my system). Ref : https://stackoverflow.com/questions/66673759/git-branch-m-main

I was wondering instead of moving/renaming the branch by default ( here we are also making assumption that branch is not named as main by default) why don't we tell to create branch main by default when initializing the repo

So instead of 
```javascript
 await execa("git", ["init"], {
    cwd: creationDirectory,
   });
```

why dont we use 
```javascript
 await execa("git", ["init" ,"-b","main"], {
    cwd: creationDirectory,
   });
```
and get rid of
```javascript
 await execa("git", ["branch", "-m", "main"], {
            cwd: creationDirectory,
          });
```

**Comment by petebacondarwin** [comment]
We recently moved away from `init -b main` because of a lack of support in older versions of git.
It seems this new approach is not flawless either.

From what I read, as long as we create an initial commit then we would be safe to rename the branch.
This actually seems like a sensible thing to do in any case - i.e. commit the first set up of code generated by `wrangler init`.

**Comment by sunilhari** [comment]
Okay got it.So the idea would be to commit the initial files that get generated like`wrangler.toml`
