### ISSUE TITLE
🐛 BUG: No loader is configured for ".rs"

### ISSUE THREAD

**Issue by lnxcz** [cloudflare/wrangler2#1439]
### What version of `Wrangler` are you using?

2.0.16

### What operating system are you using?

Fedora Linux 36

### Describe the Bug

Hey, just started using workers with Rust. When using wrangler I always get error if I want to start a development server using `wrangler dev src/lib.rs --local` (`npm run dev`) in [workers-rs](https://github.com/cloudflare/workers-rs). It does compile the project into a `build/` folder, but then i got this error.
```
⛅️ wrangler 2.0.16
--------------------
Running custom build: cargo install -q worker-build && worker-build --release
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.04s
[INFO]: Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: :-) Done in 2.45s
[INFO]: :-) Your wasm pkg is ready to publish at /home/lynx/code/rust/workers/build.
✘ [ERROR] No loader is configured for ".rs" files: src/lib.rs


✘ [ERROR] Build failed with 1 error:

  error: No loader is configured for ".rs" files: src/lib.rs
```
I didnt modify anything from original workers-rs source, just installed deps and ran dev script.

**Comment by threepointone** [comment]
It looks like you used the instructions from [`workers-rs`](https://github.com/cloudflare/workers-rs#getting-started) to create your project. I see the problem here: 
- The template that's being used, uses `src/lib.rs` as the entry point. wrangler doesn't support `.rs` files as entry points. This is reported here as well https://github.com/cloudflare/templates/issues/75
  - The fix is to make this change inside `package.json`
  ```diff
    "scripts": {
  -    "deploy": "wrangler publish src/lib.rs",
  -    "dev": "wrangler dev src/lib.rs --local"
  +   "deploy": "wrangler publish build/worker/shim.mjs", 
  +    "dev": "wrangler dev build/worker/shim.mjs --local"
    },
  ```
- I'll send a fix to the templates repository early next week, unless @zebp beats me to it. 
- Closing this issue since it isn't a wrangler issue per se, but let me know if that suggested fix doesn't work for you.

**Comment by oscartbeaumont** [comment]
This still doesn't seem to be fixed when you run `pnpm create cloudflare my-project worker-rust`. Would be good to get a fix out.

**Comment by Salzian** [comment]
Fix is waiting for a review 🥲 
https://github.com/cloudflare/templates/pull/80
