### ISSUE TITLE
🚀 Feature Request: support source maps in `wrangler dev`

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wrangler2#1509]
### Describe the solution

Add source maps!!

**Comment by cameron-robey** [comment]
https://github.com/cloudflare/wrangler2/issues/441

How are these going to interact, is there a nice way to link them together?

**Comment by huw** [comment]
Hey mate—#1535 breaks source maps in `--local` mode, because it overrides `sourceRoot` like this  #([bundle.ts#L196](https://github.com/cloudflare/wrangler2/blob/7ae059b3dcdd9dce5f03110d8ff670022b8ccf02/packages/wrangler/src/bundle.ts#L196)):

```json
{
  sources: ["../tmp-<example>/checked-fetch.ts", "../../<path-to-src-root>/<file>.js"],
  sourceRoot: "<path-to-src-root>"
}
```

When debugging in local dev mode, this tries to resolve `../../<path-to-src-root>/<file>.js` relative to `<path-to-src-root>`, which fails. Removing `sourceRoot: entryDirectory` fixes this.

But I notice you use the `sourceRoot` value when outputting errors in [inspect.ts#L320](https://github.com/cloudflare/wrangler2/blob/eee7333b47d009880b8def8cf4772b6d5fcf79e9/packages/wrangler/src/inspect.ts#L320). My suggestion is that we reconcile these by removing `sourceRoot: entryDirectory` and using `path.resolve(<sourceRoot>, <source>)` to get the correct filename for the error. Alternatively, we could pass a check for `local` into ESBuild, but the first solution is probably more idiomatic.

Workaround for now is to use a custom build with wrangler and pass `--no-bundle`.

Happy to write up an issue, I’ll probably pull together a PR with my suggestion tomorrow if it’s feasible to do so (& I have the time).

**Comment by BillBrower-Shopify** [comment]
@huw Did this ever get resolved for `--local` ? We still see sourcemaps from Wrangler that point to things like `index.js:223469:38` rather than the correct files

**Comment by petebacondarwin** [comment]
@penalosa ?

**Comment by huw** [comment]
In my case, I’m waiting for cloudflare/workerd#371 before I can test this.

**Comment by BillBrower-Shopify** [comment]
Hi @huw this happens on both v2 local and v3 local. In both cases the stack traces end up looking like this

```
TypeError: Cannot read properties of undefined (reading 'propertyName')
    at ComponentName (index.js:292996:187)
    at renderWithHooks (index.js:98065:24)
    at renderIndeterminateComponent (index.js:98122:24)
    at renderElement (index.js:98278:15)
    at renderNodeDestructiveImpl (index.js:98382:17)
    at renderNodeDestructive (index.js:98362:22)
    at renderIndeterminateComponent (index.js:98158:15)
    at renderElement (index.js:98278:15)
    at renderNodeDestructiveImpl (index.js:98382:17)
    at renderNodeDestructive (index.js:98362:22)
```

**Comment by aleclarson** [comment]
I believe this should be reopened. It appears the wrangler-produced sourcemap is not being used on the `wrangler dev` stack trace.

**Comment by airtonix** [comment]
yep also seem to be suffering this

**Comment by petebacondarwin** [comment]
@airtonix or @aleclarson - please can you provide a reproduction of the problem that we can debug and open a new issue with steps to reproduce.

**Comment by schickling** [comment]
Seems like setting the following in the `wrangler.toml` makes `wrangler dev` respect my source maps:

```toml

[build]
# Enable source maps for better debugging
command = ""
```
