### ISSUE TITLE
Worker cannot find secret and shows secret not defined

### ISSUE THREAD

**Issue by felixgogo** [cloudflare/wrangler2#1941]
#### Describe the bug
Wrangler command line can put secret.
However, Worker cannot find this secret.

#### Reproduce the bug
1. wrangler generate helloworld
2. wrangler dev
works fine here
3. wrangler secret put MYSECRET
4. wrangler secret list
MYSECRET is shown
5. Update index.js with return new Response(`Hello World! ${MYSECRET}`);
6. CTRL-C and wrangler dev
Browser at 127.0.0.1:8787 shows ReferenceError MYSECRET is not defined
7. CTRL-C and wrangler publish
Secret is in console., but Worker still shows  MYSECRET not defined

#### Expected behavior
MYSECRET is shown in wrangler command line and should be defined in Worker.

#### Environment and versions
* operating system: MacOS Monterey 12.6 & Windows10
* output of `wrangler -V`: 2.1.6
* output of `node -v`: v16.17.0
* content of `wrangler.toml`:
name = "helloworld"
main = "src/index.js"
compatibility_date = "2022-09-23"
account_id = "xxxxxxxxxxxxxxxxxxxxx"
workers_dev = true

**Comment by cameron-robey** [comment]
Hi there 👋 ! 
Thanks for raising this issue - I've transferred it into the `wrangler2` repository as that is the version you are using.

To answer the issue, this is due to the way that environment is handled between the two different syntax's we have for workers.

When you run `wrangler generate helloworld` this creates a worker using the **modules** syntax. The other option is the **service worker** syntax.

One of the main differences between the two is how they handle environment variables. If you were using the service worker syntax, then how you are accessing these environment variables or secrets is correct. For the module syntax, however, your environment variables are found on the `env` parameter passed into your `fetch` handler.

So to access the secret `MYSECRET` you will need to use `env.MYSECRET`.

Here are some examples, and some links to our docs for further reference.

```js
export default {
  async fetch(request, env, ctx) {
    return new Response(`Hello World! ${env.MYSECRET}`);
  },
};
```

- [Fetch event: modules syntax](https://developers.cloudflare.com/workers/runtime-apis/fetch-event/#syntax-module-worker)
- [Introducing modules workers](https://blog.cloudflare.com/workers-javascript-modules/)
- [Migrating to modules workers](https://developers.cloudflare.com/workers/learning/migrating-to-module-workers/)
- [Using service worker syntax](https://developers.cloudflare.com/workers/learning/service-worker/)

Let us know if you have any more questions!

**Comment by felixgogo** [comment]
> Hi there 👋 ! Thanks for raising this issue - I've transferred it into the `wrangler2` repository as that is the version you are using.
> 
> To answer the issue, this is due to the way that environment is handled between the two different syntax's we have for workers.
> 
> When you run `wrangler generate helloworld` this creates a worker using the **modules** syntax. The other option is the **service worker** syntax.
> 
> One of the main differences between the two is how they handle environment variables. If you were using the service worker syntax, then how you are accessing these environment variables or secrets is correct. For the module syntax, however, your environment variables are found on the `env` parameter passed into your `fetch` handler.
> 
> So to access the secret `MYSECRET` you will need to use `env.MYSECRET`.
> 
> Here are some examples, and some links to our docs for further reference.
> 
> ```js
> export default {
>   async fetch(request, env, ctx) {
>     return new Response(`Hello World! ${env.MYSECRET}`);
>   },
> };
> ```
> 
>     * [Fetch event: modules syntax](https://developers.cloudflare.com/workers/runtime-apis/fetch-event/#syntax-module-worker)
> 
>     * [Introducing modules workers](https://blog.cloudflare.com/workers-javascript-modules/)
> 
>     * [Migrating to modules workers](https://developers.cloudflare.com/workers/learning/migrating-to-module-workers/)
> 
>     * [Using service worker syntax](https://developers.cloudflare.com/workers/learning/service-worker/)
> 
> 
> Let us know if you have any more questions!

Thank you for the explanation. 
After adding env as you suggested, I was able to get my secret value via an url got from running wrangler publish.
However, the local mode, after running wrangler dev, still shows me "undefined".
Just want to know if this local mode cannot get the secret value.

**Comment by petebacondarwin** [comment]
Local mode does not interact with the internet at all, so it cannot see any secrets you have uploaded.
The approach you need to use is to add dummy secret values to a file called `.dev.vars`, which has the same format as a `.env` file. This file is read by `wrangler dev -l` and the variables defined there appear as variables in the Worker.

**Comment by felixgogo** [comment]
> Local mode does not interact with the internet at all, so it cannot see any secrets you have uploaded. The approach you need to use is to add dummy secret values to a file called `.dev.vars`, which has the same format as a `.env` file. This file is read by `wrangler dev -l` and the variables defined there appear as variables in the Worker.

Thank you! no further questions.
