### ISSUE TITLE
🐛 BUG: Wrangler metrics uses ~/.wrangler even if XDG directory is available 

### ISSUE THREAD

**Issue by YaBoiBurner** [cloudflare/wrangler2#2075]
### What version of `Wrangler` are you using?

2.1.13

### What operating system are you using?

Linux

### Describe the Bug

Wrangler has an XDG compliant directory it tries to use (`$XDG_CONFIG_HOME/.wrangler`) when it can, but the metrics code ignores this setting.
This seems to be caused by the metrics settings not actually using the correct global config directory.

Wrangler sets the global config dir here:
https://github.com/cloudflare/wrangler2/blob/wrangler@2.1.13/packages/wrangler/src/global-wrangler-config-path.ts#L15-L26

However, metrics are hardcoded to use `~/.wrangler` here:
https://github.com/cloudflare/wrangler2/blob/wrangler@2.1.13/packages/wrangler/src/metrics/metrics-config.ts#L166-L171

**Comment by YaBoiBurner** [comment]
Should I be concerned about this? https://github.com/cloudflare/wrangler2/actions/runs/3316894321/jobs/5479191044

**Comment by JacobMGEvans** [comment]
@petebacondarwin Do you remember if you hardcoded the pathing rather than the XDG compliant pathing?

**Comment by petebacondarwin** [comment]
Hard-coded - sorry.

https://github.com/cloudflare/wrangler2/blob/670fa778db263a3cf81b2b1d572dcb0df96a0463/packages/wrangler/src/metrics/metrics-config.ts#L170

**Comment by x-yuri** [comment]
Let me add what it affects.

```
$ rm -r ~/.wrangler ~/.config/.wrangler
$ npx wrangler login
```

It [creates][b] [both][c]:

```
~/.config/.wrangler/config/default.toml
~/.wrangler/config/metrics.json
```

If you run `npx wrangler login` again, it won't find `default.toml` because `~/.wrangler` [exists][a]. Of course in place of the second login there can be `npx wrangler pages project create` or something. That is, to log in you need to log in twice.

On a side note, it'd be nice if there was a way to avoid all interactivity. Things like:

> Would you like to help improve Wrangler by sending usage metrics to Cloudflare? (y/n)
> Enter the production branch name: production

And an ability to specify no branch.

[a]: https://github.com/cloudflare/wrangler2/blob/wrangler%402.1.15/packages/wrangler/src/global-wrangler-config-path.ts#L21
[b]: https://github.com/cloudflare/wrangler2/blob/wrangler%402.1.15/packages/wrangler/src/global-wrangler-config-path.ts#L24
[c]: https://github.com/cloudflare/wrangler2/blob/wrangler%402.1.15/packages/wrangler/src/metrics/metrics-config.ts#L170
