### ISSUE TITLE
🐛 A request to the Cloudflare API failed

### ISSUE THREAD

**Issue by repbaprotonme** [cloudflare/wrangler2#2426]
### What version of `Wrangler` are you using?

2.0.08

### What operating system are you using?

Chromebook

### Describe the Bug

A request to the Cloudflare API (/accounts/41f6f507a22c7eec431dbc5e9670c73d/workers/scripts/work/routes) failed.

I added this to .bashrc
export CLOUDFLARE_API_TOKEN=RO-GuzNu0c3LO8e7OWzK1e_pXBULU9uLkydCmyei   

I CANNOT use a browser for authentiification.

**Comment by repbaprotonme** [comment]
I'm actually using arch linux on a remote server without access to a browser for authentification.    I need to authenticate using a token but its not working.

**Comment by repbaprotonme** [comment]
Fixed

**Comment by mrbm** [comment]
@repbaprotonme what was your resolution?

**Comment by broofa** [comment]
Dropping a breadcrumb here, as I found the "A request to the CloudFlare API ... failed" error a bit confusing in some contexts. Specifically, I ran into this while running `wrangler publish` on a project using TypeScript and received the following:

<img width="850" alt="CleanShot 2023-02-12 at 05 56 18@2x" src="https://user-images.githubusercontent.com/164050/218315558-7382cdf7-f213-4815-bb80-f145945d1a74.png">

The problem here is that nothing about this error looks familiar.  The loud portion of the error (red and bold) isn't directly relevant; it's just `wrangler` telling you that something went wrong with a request it made to CF's servers. And the actual problem (in the text below that) is no more helpful;  My project didn't have a "worker.js" file, nor was could I find a reference to `global` anywhere obvious.  Not even in the bowels of my `node_modules`.  (The problem ended up being in a dependency pulled in from node_modules *above* my worker project.)

### Solution

After [some asking around](https://discord.com/channels/595317990191398933/799437470004412476/1073776927111905331) I eventually figured out that running `wrangler publish --dry-run --outdir=some_temp_folder` would save the file(s) `wrangler` was attempting to upload locally where I could inspect them.  And, wonder of wonders, there was a `worker.js` file with the offending line in it and, right above that, a comment showing the original source file:

<img width="630" alt="image" src="https://user-images.githubusercontent.com/164050/218325654-a8103b2a-230c-4c16-b6a6-716a6c38ea6f.png">
