### ISSUE TITLE
🐛 BUG: Error: Pages only supports files up to 26.2 MB in size

### ISSUE THREAD

**Issue by kwaimind** [cloudflare/wrangler2#2516]
### Which Cloudflare product(s) does this pertain to?

Pages, Workers/Other, Wrangler

### What version of `Wrangler` are you using?

2.x.x

### What operating system are you using?

Cloudflare UI

### Describe the Bug

Error occurs when deploying in the Cloudflare dashboard so can't give an accurate Wrangler version. Deployment ID: `6d852cdd-fe43-4dac-bb52-f7b124dc555a`

--

Hey there, I'm investigating whether I can switch my current Next.js hosting from Vercel to Cloudflare Pages. 

However, when deploying the app I get the following error:

```
09:19:15.658 | ✘ [ERROR] Error: Pages only supports files up to 26.2 MB in size
09:19:15.658 | cache/webpack/client-production/0.pack is 42.2 MB in size
```

I tried upgrading my account to a paid plan but that gives me the same error. 

I can try and look into making the `0.pack` file smaller, but in the meantime is it possible to increase the file size limit, and if so how can I do that? Seen in the Cloudflare forum that this might now be an option but maybe there is a way to use Cloudflare's object storage in a pages project?

Thanks for any help you can give 🫶

**Comment by WalshyDev** [comment]
Not a bug. Files can only be a max of 25 MiB - https://developers.cloudflare.com/pages/platform/limits/#file-size

Since this is just cache, you can remove it after build and avoid this issue. `<build command> && rm -rf cache`

I'd also check your output folder is correct, you don't want to be uploading cache files and I don't think they should be in your output dir.
