### ISSUE TITLE
🐛 BUG: `wrangler init [name] -y` gives you a broken tsconfig.json

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/wrangler2#2625]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.8.1

### What operating system are you using?

Mac

### Describe the Bug

1. Run `npx wrangler@2.8.1 init 2023-01-26-test -y`
2. Add a tsc script to package.json: `"tsc": "tsc"`
3. Run `npm run tsc`

Error:
```
> tsc

error TS2688: Cannot find type definition file for 'jest'.
  The file is in the program because:
    Entry point of type library 'jest' specified in compilerOptions

  tsconfig.json:38:4
    38    "jest"
          ~~~~~~
    File is entry point of type library specified here.


Found 1 error.
```

tsconfig.json contains jest, but we've installed Vitest?

**Comment by mrkldshv** [comment]
Hey! I've started working on this and came across different flows of choosing test runners for TS and non-TS versions. For TS we have [Yes/No prompt](https://github.com/cloudflare/wrangler2/blob/3b932ded8c0005f23332e3bfaef15a2bdcc1a11d/packages/wrangler/src/init.ts#L527), while for non-TS version we have [select prompt](https://github.com/mrkldshv/wrangler2/blob/6b6ce5060a12e94a59c76249bb8022ea2737c5f7/packages/wrangler/src/init.ts#L635) with two options where user can pick Jest or Vitest. Is it intentional? Should we unify it?

**Comment by rozenmd** [comment]
Hey @mrkldshv thanks for looking into this - there are two different types of prompts at the moment because `vitest` is the only option for TypeScript, while `jest` and `vitest` are options for JavaScript (because it's non-trivial to set-up TypeScript with Jest - you also need to install babel if you want types to work properly)

**Comment by mrkldshv** [comment]
Got it, thanks! I also noticed that we add test runner types to the config even if we opt out of installing one for the project. I guess it's somewhat related to https://github.com/cloudflare/wrangler2/issues/2593. So I can skip it for now, and only replace `jest` with `vitest` in the config.

**Comment by rozenmd** [comment]
Fixed by https://github.com/cloudflare/wrangler2/pull/2652
