### ISSUE TITLE
KV assets doesn't upload for Workers Sites 

### ISSUE THREAD

**Issue by fcomrqz** [cloudflare/wrangler2#344]
I tried to use Workers Sites with your example on this repo `wrangler2/packages/example-sites-app` and doesn't works. 

It fails to upload assets to KV for `dev` and `publish` commands.

Is pending work or you will deprecate Workers Sites in favor of Pages?

**Comment by fcomrqz** [comment]
I get this email after trying to publish like ten times. 😳

> Hi,
> 
> You have exceeded the daily Cloudflare Workers KV free tier limit of 1000 Workers KV list operations.
> 
> Requests to list values from the Workers KV API will return 429 errors and list operations within a Worker will fail until the limit resets at 2022-01-31 at 00:00:00 UTC.
> 
> You can restore service by upgrading your account (Mondraco) to Workers Bundled on the plans page. It has a minimum monthly billing amount of $5, which includes 10 million read operations and 1 million each of write, delete, and list operations.
> 
> Best,
> The Cloudflare Workers Team

**Comment by threepointone** [comment]
Extremely sorry about this. We had a bug with Sites that was fixed in https://github.com/cloudflare/wrangler2/pull/335, but wasn't released to the `beta` channel. I just did a `beta` release right now (`0.0.15`), so it should be resolved now. 

We are going to be supporting Sites for a while longer, until we have a better solution (which will potentially be an ad hoc Pages solution, but we haven't made any plans concrete just yet. We don't expect to ship any _new_ features for Sites. The implementation is close to feature complete (pending landing https://github.com/cloudflare/wrangler2/pull/338, and anything else we missed). 

I'm going to close this issue, but let me know if you face any further problems.

**Comment by threepointone** [comment]
Starting a discussion re: Sites and other options to serve static assets here - https://github.com/cloudflare/wrangler2/issues/346

**Comment by fcomrqz** [comment]
Thank you for fixing the assets upload!

But I can't use `wrangler2` with KV assets with ES Modules worker.

Is it possible?

I understand that should be working because you have the option documented on [cloudflare/kv-asset-handler](https://github.com/cloudflare/kv-asset-handler#es-modules) repo. Maybe I didn't understand.

**Comment by threepointone** [comment]
That's surprising, it should work. I'll reopen this and investigate soon.

**Comment by fcomrqz** [comment]
With `wrangler@0.0.18` it's working properly. 😁
