### ISSUE TITLE
Flakey tests

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler2#361]
### What version of `Wrangler` are you using?

N/A

### What operating system are you using?

N/A

### Describe the Bug

https://github.com/cloudflare/wrangler2/runs/5022637425?check_suite_focus=true

Looks like there's a couple of tests that might be flakey.

**Comment by petebacondarwin** [comment]
This is because the ` should offer to install type definitions in an existing typescript project (30003 ms)` test is actually running `npm install`, which in this case ran longer than the 30 secs timeout.
This commit (https://github.com/cloudflare/wrangler2/pull/329/commits/d499c4d6cca53702c8d6ba0c5a8a6248b6bdec4d) from my #329 PR will resolve that.

**Comment by petebacondarwin** [comment]
Closing now that #329 has landed.
