### ISSUE TITLE
🐛 BUG: build.upload dir doesn't default to dist

### ISSUE THREAD

**Issue by taylorlee** [cloudflare/wrangler2#488]
### What version of `Wrangler` are you using?

0.0.17

### What operating system are you using?

Linux

### Describe the Bug

Not sure if this is a bug, but docs say `[build.upload]`'s `dir` is optional and defaults to `dist`. 
https://developers.cloudflare.com/workers/cli-wrangler/configuration#modules
in wrangler2 this defaults to the project dir, so module users will need to manually add:
```
[build.upload]
dir = "dist"
```
to keep their custom builds working.

Not sure if we should change wrangler2 or the docs? Defaulting to dist in the first place is arguably confusing and maybe being explicit is preferable.

**Comment by threepointone** [comment]
Yeah we definitely don't want `./dist` to be the default, that's caused a lot of angst. Perhaps the thing to do here is to make `build.upload.dir` mandatory if you're using `build.upload.main`. 

Overall, we want to move away from this and have a top level `main` field for both service worker and modules format workers (since we can now infer format and have a first class module system in w2). 

Thanks for filing this issue!

**Comment by petebacondarwin** [comment]
Backward compat is hard...

If we are going to deprecate the `build.upload.main/dir` fields in favour of a top-level `main/entry` field, then perhaps we could leave `dir` defaulting to `dist`? But only if we work hard to move people off the` build.upload` approach.

**Comment by Electroid** [comment]
> Backward compat is hard...
> 
> If we are going to deprecate the `build.upload.main/dir` fields in favour of a top-level `main/entry` field, then perhaps we could leave `dir` defaulting to `dist`? But only if we work hard to move people off the` build.upload` approach.

I think this is a good idea. Existing configurations will work and we can fix this with a new `entry` or `main` field.
