### ISSUE TITLE
feature: `--watch` mapped to Miniflare `buildWatchPaths`

### ISSUE THREAD

**Issue by jacob-ebey** [cloudflare/wrangler2#49]
To support cases where you import generated modules into your `functions` scripts we need to be able to pass additional watch files/directories to Miniflare.

**Comment by threepointone** [comment]
This might already work, since we're using esbuild in watch mode (I think?)

**Comment by rkusa** [comment]
It doesn't work for me at least, which is why I've opened #71. Looking into the code, it runs `npx @cloudflare/pages-functions-compiler build ${functionsDirectory} --outfile ${scriptPath}` each time something in the functions directory changes (https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/pages.tsx#L240-L241). `npx @cloudflare/pages-functions-compiler` isn't using esbuild in watch mode as far as I can tell from looking at the source in `node_modules` (package is not open source yet I think).

**Comment by threepointone** [comment]
I'll have a look at this and your attached PR early next week, thanks!

**Comment by GregBrimble** [comment]
For anyone following this issue, I've just made a comment on this related PR: https://github.com/cloudflare/wrangler2/pull/71#issuecomment-997211744

I'm working on it right now, so we'll hopefully have something which automatically picks up these dependent files up shortly.
