### ISSUE TITLE
support `NODE_PATH` / `nodePaths`

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#55]
Not all modules will be under `node_modules`, especially in scenaros where folks vendor modules into their own repo. We should support passing NODE_PATH as an env var or `nodePaths` as config.

**Comment by petebacondarwin** [comment]
The Node.js docs suggest that NODE_PATH is legacy and not really how things should be done.

Given that we are able to compile TypeScript, it would also be necessary to add to the `"paths"` mapping property in tsconfig.json so that TSC can also find the dependencies.
So I think the best way to solve this would be to implement (either ourselves or using a library) an esbuild plugin that does something like: https://www.npmjs.com/package/@esbuild-plugins/tsconfig-paths

**Comment by threepointone** [comment]
I checked, and esbuild reads from compilerOptions.paths already, so the plug-in shouldn't be necessary 

I agree with you original point. Could just close this for now, or revisit in 2.1

**Comment by petebacondarwin** [comment]
Let's close this and reopen if someone finds a scenario we don't support out-of-the-box.
