### ISSUE TITLE
WebSocket support for wrangler pages dev

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler2#70]
WebSockets aren't working on pages dev at the moment. Probably something to do with the way we're MITM-ing requests.

**Comment by edwellbrook** [comment]
Hi! I came across this issue because I found WS requests were not working, which breaks hot reloading for some dev tools.

It does appear that the issue is with how requests are proxied. The `wrangler pages dev -- {command}` command will look up the port number for `{command}` and then make `fetch` requests to the resource directly: https://github.com/cloudflare/wrangler2/blob/fc112d74fe212f32e585865df96999a894062801/packages/wrangler/src/pages.tsx#L899-L901

**Comment by bennor** [comment]
I tried to work around this by proxying in the other direction (using Next.js rewrites) and that works and HMR works as expected, but for some reason I still get the logs littered with the following: 

```
GET /_next/webpack-hmr 404 Not Found (2.51ms)
[pages:err] TypeError: Web Socket request did not return status 101 Switching Protocols response with Web Socket
```

Any idea why wrangler would be intercepting these requests? The request URL in the browser dev tools is `ws://localhost:3000/_next/webpack-hmr`

**Comment by HamishWHC** [comment]
Any updates on this? If not does anyone know of workarounds (early enough I could switch from Next.js if I must)? Would like to get this working in my project.
