### ISSUE TITLE
feature: build.watch_dir should capture TSConfig path mapping

### ISSUE THREAD

**Issue by vlovich** [cloudflare/wrangler2#703]
### What version of `Wrangler` are you using?

0.0.19

### What operating system are you using?

Linux

### Describe the Bug

I have an ESBuild TypeScript project. In my build.mjs file I have:
```
import { TsconfigPathsPlugin } from '@esbuild-plugins/tsconfig-paths'
```
and
```
plugins: [TsconfigPathsPlugin({tsconfig: './tsconfig.json'})],
```

In my tsconfig I have:
```
     "baseUrl": ".",
     "paths": {
       "~lib/*": ["../lib/*"]
     }
```

However, when I modify files in `../lib` no changes are picked up. Only changes in src. Wrangler.toml:
```
name = "my-project"
compatibility_date = "2022-03-13"
usage_model = "unbound"
workers_dev = true
main = "build/worker.mjs"

[build]
command = "npm run build"
```
The build command simply calls `node build.mjs`

**Comment by threepointone** [comment]
`wrangler` custom builds are pretty simplistic, you can define a custom build `command`, and a `watch_dir` (that defaults to `./src`). There are a few things we (wrangler) could/should do here - 

- let `watch_dir` optionally be an array, so you can pass multiple values to it. 
- read `compilerOptions.paths` values from `tsconfig.json` and add it to `watch_dir` automatically
- we should probably also let folks define a path to a custom `tsconfig` in `wrangler.toml` 

This probably won't make it into the imminent RC build, but we should do it sooner than later. 

--- 

btw, separate from the watch problem, I don't think the plugin is necessary? esbuild reads `paths` and resolves it correctly. I made a simplified version of your code and it appears to bundle correctly https://github.com/threepointone/tsconfig-esbuild-paths-test

**Comment by threepointone** [comment]
Some quick notes - 
- when not using custom builds, we do resolve `paths` in `tsconfig.json` and restart the dev server when any files change 
- we also accept a path to a custom `tsconfig.json` now (via `--tsconfig` / `config.tsconfig`)
- we also accept `config.build.watch_dir` to be an array of paths now (in `@beta`, rolling out to prod soon)
- when using custom builds, we _cannot_ read from tsconfig, since we won't even know it's a typescript project after the custom build is run. The recommendation there is to manually setup `config.build.watch_dir`

So I think we've done what we can here, it's definitely better. Closing this issue!
