### ISSUE TITLE
🐛 BUG: `wrangler2 login` doesn't work with Cloudflare Gateway WARP

### ISSUE THREAD

**Issue by cmackenzie1** [cloudflare/wrangler2#742]
### What version of `Wrangler` are you using?

0.0.24

### What operating system are you using?

Mac

### Describe the Bug

```bash
node --version
v16.14.2
```

## Steps to reproduce
```bash
wrangler2 login
# browser opens a new window, click accept
 ⛅️ wrangler 0.0.24 
--------------------
Attempting to login via OAuth...
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: fetch failed
    at Object.processResponse (/Users/cole/.nvm/versions/node/v16.14.2/lib/node_modules/wrangler/wrangler-dist/cli.js:106815:34)
    at Fetch.fetchFinale (/Users/cole/.nvm/versions/node/v16.14.2/lib/node_modules/wrangler/wrangler-dist/cli.js:107145:21)
    at Fetch.mainFetch (/Users/cole/.nvm/versions/node/v16.14.2/lib/node_modules/wrangler/wrangler-dist/cli.js:107039:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Timed out waiting for authorization code, please try again.
```

Turning WARP into Gateway with DoH mode allows login to proceed.

**Comment by threepointone** [comment]
Good catch, we should fix this.

**Comment by mattbdc** [comment]
To add the help doesnt mention the wrangler login command, since its a first level command it should be included here I think? 

```

➜  projectx git:(main) ✗ $(npm bin)/wrangler             
wrangler

Commands:
  wrangler init [name]       📥 Create a wrangler.toml configuration file
  wrangler whoami            🕵️  Retrieve your user info and test your auth config
  wrangler dev [script]      👂 Start a local server for developing your worker
  wrangler publish [script]  🆙 Publish your Worker to Cloudflare.
  wrangler tail [name]       🦚 Starts a log tailing session for a published Worker.
  wrangler secret            🤫 Generate a secret that can be referenced in the worker script
  wrangler kv:namespace      🗂️  Interact with your Workers KV Namespaces
  wrangler kv:key            🔑 Individually manage Workers KV key-value pairs
  wrangler kv:bulk           💪 Interact with multiple Workers KV key-value pairs at once
  wrangler pages             ⚡️ Configure Cloudflare Pages
  wrangler r2                📦 Interact with an R2 store


```

**Comment by mattbdc** [comment]
```
$(npm bin)/wrangler login --help
wrangler login

Flags:
  -c, --config      Path to .toml configuration file  [string]
  -h, --help        Show help  [boolean]
  -v, --version     Show version number  [boolean]
      --legacy-env  Use legacy environments  [boolean]

Options:
      --scopes-list  List all the available OAuth scopes with descriptions
      --scopes       Pick the set of applicable OAuth scopes when logging in  [array]
```

Similar to how other CLI and desktop tooling using oauth2 works we need to have options to have the login challenge avoid opening in the default browser, show URL will suffice.

**Comment by threepointone** [comment]
> To add the help doesn't mention the wrangler login command, since its a first level command it should be included here I think?

This is fixed in alpha via https://github.com/cloudflare/wrangler2/pull/699. 

Good points about the environments where you can't open a browser, etc. We currently support an env var `CLOUDFLARE_API_TOKEN=token` (https://developers.cloudflare.com/api/tokens/create/) which will bypass the whole login system, and we'll document that. Likely also add a cli option at some point like you suggested. 

These points aren't super connected to the original issue tho, so I'd recommend you file a separate issue if you'd like to track these.

**Comment by petebacondarwin** [comment]
Isn't this a problem with WARP rather than Wrangler? Should we raise an issue with them?
The help now shows `login` as a command.
The https://github.com/cloudflare/wrangler2/issues/23 issue covers the problem of not being able to open a browser in some environments.

Closing as the additional points are either resolved or tracked elsewhere; and the main point is arguably not actionable by Wrangler?

**Comment by threepointone** [comment]
We fixed this properly in https://github.com/cloudflare/wrangler2/pull/963
