### ISSUE TITLE
🐛 BUG: Miniflare KV persistence not working in Wrangler2 --local mode

### ISSUE THREAD

**Issue by hkochniss** [cloudflare/wrangler2#766]
### What version of `Wrangler` are you using?

0.0.24

### What operating system are you using?

Mac OS (ARM64)

### Describe the Bug

It seems as Wrangler2 uses Miniflare under the hood in --local mode, many Miniflare features should work, especially persistence around KV etc. But for some reason persistence doesn't kick in when using 

```
[miniflare]
kv_persist = true
```

in wrangler.toml. Also other kv_persist options don't work, KV namespace are just empty on each change of a worker file. This really hurts productivity, I'm assuming this is unintended and should work?

Using typescript and modules, can provide a minimal reproduction case once this is confirmed as a bug.

**Comment by threepointone** [comment]
Try this cli flag: `--experimental-enable-local-persistence`

**Comment by hkochniss** [comment]
A bit better, but unfortunately only works i  between worker changes, does not persist to disk

so this flag solves the problem of loosing KV data between worker changes (when it restarts the mf server in watch mode), but once I stop wrangler 2 and start again, the KV data is lost. Also I can't find anything written to disk visible, not in ./mf/kv or anywhere else, so I assume this is in-memory persistence for now (or I'm overlooking a secret folder somewhere, still new to the Mac ecosystem)? 

How is this intended to work right now? Is there any roadmap/plans around offline persistence? I feel there isn't much missing feature wise (only let Miniflare do it's thing), but maybe I'm missing something

**Comment by threepointone** [comment]
We'd only just started working on this, hence the experimental flag. What the flag does, is enable persistence for kv/durable_objects/cache in miniflare https://github.com/cloudflare/wrangler2/blob/ed4f2ef00f86374ac7d1ac6ff072d939c80b6c18/packages/wrangler/src/dev/local.tsx#L163-L170
This does persist to disk. However, we use a fresh temp directory where the actual worker is bundled, and that temp directory disappears when you close wrangler dev. Instead, we should be persisting to a path relative to the working directory, so that it sticks around in a known location (and let users like you decide what to do with the generated files). I'll send a fix for this soon. 

The workaround for now if you want to test persistence, is to use regular "remote" mode. But we'll fix it very soon!

**Comment by hkochniss** [comment]
Oh cool, that sounds like a big improvement. Also props for the late reply, knowing your timezone is London ;)
