### ISSUE TITLE
🐛 BUG: "r2" added incorrectly to help messages when using invalid r2 subcommands

### ISSUE THREAD

**Issue by jahands** [cloudflare/wrangler2#871]
### What version of `Wrangler` are you using?

0.0.27

### What operating system are you using?

WSL (ubuntu 20.04, ext4 filesystem)

### Describe the Bug

`npx wrangler@beta r2 asdf` outputs the following help message:

```
Commands:
  wrangler r2 init [name]       📥 Create a wrangler.toml configuration file
  wrangler r2 dev [script]      👂 Start a local server for developing your worker
  wrangler r2 publish [script]  🆙 Publish your Worker to Cloudflare.
  wrangler r2 tail [name]       🦚 Starts a log tailing session for a published Worker.
  wrangler r2 secret            🤫 Generate a secret that can be referenced in the worker script
  wrangler r2 kv:namespace      🗂️  Interact with your Workers KV Namespaces
  wrangler r2 kv:key            🔑 Individually manage Workers KV key-value pairs
  wrangler r2 kv:bulk           💪 Interact with multiple Workers KV key-value pairs at once
  wrangler r2 pages             ⚡️ Configure Cloudflare Pages
  wrangler r2 r2                📦 Interact with an R2 store
  wrangler r2 login             🔓 Login to Cloudflare
  wrangler r2 logout            🚪 Logout from Cloudflare
  wrangler r2 whoami            🕵️  Retrieve your user info and test your auth config

Flags:
  -c, --config      Path to .toml configuration file  [string]
  -h, --help        Show help  [boolean]
  -v, --version     Show version number  [boolean]
      --legacy-env  Use legacy environments  [boolean]

Unknown argument: asdf
```

"asdf" can be replaced with any invalid subcommand of "r2".

"r2" should not be added as a prefix for all of these commands in the help message

**Comment by threepointone** [comment]
lol, great catch.

**Comment by JacobMGEvans** [comment]
oh that's interesting

**Comment by JacobMGEvans** [comment]
Found the section of [code] (https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/index.tsx#L2415-L2419) responsible since it is a `unknown argument` it gets caught at in a [top-level `.fail()`](https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/index.tsx#L214-L220) yargs function that rethrows the error. Likely the solution should be creating a `.fail()` helper function similar to the `.command(subHelp)` that can be used with all the commands which will have the context of the subCommand `makeCLI.argsv` which is lost at the top level
